import = [
  "~/.config/alacritty/themes/gruvbox.toml"
]

[env]
TERM = "xterm-256color"
TERM_PROGRAM = "alacritty"

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 11

[font.normal]
family = "SpaceMono Nerd Font"

[window]
decorations = "buttonless"
dynamic_title = true
option_as_alt = "Both"

[window.dimensions]
columns = 125
lines = 35

[window.padding]
x = 10
y = 10

[[keyboard.bindings]]
action = "None"
key = "w"
mods = "Super"

[[keyboard.bindings]]
action = "None"
key = "t"
mods = "Super"
