#!/bin/bash

selected=$(
(
find /usr/share/icons -type f \( -iname "*.svg" -o -iname "*.png" \) &&
find ~/.local/share/icons -type f \( -iname "*.svg" -o -iname "*.png" \)
) | wofi --show dmenu -I -i)

if [ ! -z "$selected" ]; then
    echo "$selected" | wl-copy
    /usr/bin/thunar "$selected"
fi

