#!/bin/bash

[ "$1" = "--" ] || exit 1

shift

TITLE="$(basename "$1")"

if [ -n "$TITLE" ]; then
  /usr/bin/wezterm -e --class "org.wezfurlong.wezterm.$TITLE" "$@"
else
  /usr/bin/wezterm -e "$@"
fi
