#!/bin/bash

# Creds: The Primeagen tmux-sessionizer:
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

# Usage
# tms [session]

function get_sessions() {
  tmux ls | grep -v '(attached)' | cut -d: -f1
  find ~/Documents/Projects -mindepth 1 -maxdepth 1 -type d &&
    find ~/Documents/Uni -mindepth 2 -maxdepth 2 -type d -not -path "*/.git/*"
}

if [[ $1 == "get_sessions" ]]; then
  get_sessions
  exit 0
fi

export FZF_DEFAULT_OPTS='
  --tmux 60%,30%
  --layout=reverse
  --prompt="Switch to session: "
  --preview="tmux list-windows -t {}"
  --preview-window=down:3:wrap
  --bind "ctrl-d:execute(tmux kill-session -t {})+reload(tms get_sessions)"
'

# If the name of an active session is given, switch to it, otherwise fuzzy find
if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(get_sessions | fzf)
fi

# If nothing is selected, simply exit
if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)

# If tmux is not running, start a new session and switch to it
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

# If there is no other session with the same name, switch to it
# -d DETACHED: don't switch
# -s Session name
# -c CWD of the session
if ! tmux has-session -t=$selected_name 2>/dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
