#!/bin/bash

# Creds: The Primeagen tmux-sessionizer: 
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

# Usage
# tms [session]


# If the name of an active session is given, switch to it, otherwise fuzzy find
if [[ $# -eq 1 ]]; then
    selected=$1
else
  selected=$(
  (
  tmux ls -F \#S &&
  find ~/Documents/code -mindepth 2 -maxdepth 2 -type d &&
  find ~/Documents/uni  -mindepth 2 -maxdepth 2 -type d -not -path "*/.git/*"
  ) | fzf )
fi

# If nothing is selected, simply exit
if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

# If tmux is not running, start a new session and switch to it
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

# If there is no other session with the same name, switch to it
# -d DETACHED: don't switch
# -s Session name
# -c CWD of the session
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
