theme = "kanabox_default"

[editor]
line-number = "relative"
rulers = [80]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode","separator", "file-name", "file-modification-indicator", "version-control"]
center = []
right = ["diagnostics", "separator", "file-encoding", "position-percentage", "file-type"]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "V"

[editor.whitespace.render]
newline = "none"
space = "none"
tab = "all"

[keys.insert]
j = {k = "normal_mode"}
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]

[keys.normal]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
