#!/usr/bin/env bash

if hyprctl monitors | grep "eDP-1" && hyprctl monitors | grep "DP-2"; then
    hyprctl keyword monitor eDP-1,disable
    killall ags
    ags & disown
else
    hyprctl keyword monitor eDP-1,2240x1400,1920x0, auto
    killall ags
    ags & disown
fi
