#!/usr/bin/env bash

function handle {
  readarray -t inputArr < <(echo "${1//>>/$'\n'}")
  if [[ ${#inputArr[@]} != 2 ]]; then
    echo "Unrecognized format: $1"
    return
  fi
  event=${inputArr[0]}
  data=${inputArr[1]}
  if [ "$event" == "monitorremoved" ]; then
      hyprctl keyword monitor "eDP-1, preferred, auto, 1.25"
      return
  elif [ "$event" == "monitoradded" ]; then
      hyprctl keyword monitor "eDP-1, disable"
      return
  fi
}

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
