#!/usr/bin/env bash

function handle {
  case "$1" in monitorremoved*)
    if ! hyprctl monitors | grep "DP-2" ; then
      hyprctl keyword monitor eDP-1,2240x1400,1920x0, auto
      killall ags
      ags & disown
    fi
  esac
}

socat - "UNIX-CONNECT:/tmp/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock" | while read -r line; do handle "$line"; done
