#!/usr/bin/env bash

workspace="$1"
action="$2"

current_monitor=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .id')

number_of_workspaces=$(hyprctl workspaces -j | jq '[.[] | select(.monitorID == '"$current_monitor"' and .windows != 0)] | length')

largest_workspace=$(hyprctl workspaces -j | jq '[.[] | select(.monitorID == '"$current_monitor"' and .windows != 0)] | max_by(.id) | .id')

if [ "$workspace" -le "$number_of_workspaces" ]; then
  if [ "$action" == "-m" ]; then
    hyprctl dispatch movetoworkspace m~"$workspace"
  else
    hyprctl dispatch workspace m~"$workspace"
  fi
else
  if [ "$action" == "-m" ]; then
    hyprctl dispatch movetoworkspace m~"$((largest_workspace + 1))"
  else
    hyprctl dispatch workspace r~$((largest_workspace + 1))
  fi
fi
